<?php

namespace ContainerKZpcJ4o;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VJjafY6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vJjafY6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vJjafY6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ripo' => ['privates', '.errored.Bv.sCkm', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $ripo argument is type-hinted with the non-existent class or interface: "App\\Controller\\PostRepository". Did you forget to add a use statement?'],
        ], [
            'ripo' => '?',
        ]);
    }
}
