<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOIWir4r\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOIWir4r/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOIWir4r.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOIWir4r\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOIWir4r\App_KernelDevDebugContainer([
    'container.build_hash' => 'OIWir4r',
    'container.build_id' => 'b1ad8209',
    'container.build_time' => 1643196949,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOIWir4r');
